# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
