# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('task_status', models.CharField(default='waiting', max_length=9)),
            ],
            options={
                'db_table': 'task_logs',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=32)),
                ('task_type', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('loop_max', models.IntegerField(max_length=9)),
                ('job_id', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='task_logs',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks'),
        ),
    ]
