# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boo_commander', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boo_commander',
            table='boo_commander',
        ),
    ]
