# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boo_commander', '0003_auto_20170831_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boo_commander',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
